### ISSUE TITLE
GTM KIT doesn't recognize Easy Digital Downloads (pro)

### ISSUE THREAD

**Issue by pety-dc** [tlamedia/gtm-kit#127]
EDD warns to activate PRO version (when you have license)

It then deactivates the "normal" plugin and activates a pro version

![image](https://user-images.githubusercontent.com/25766885/232853686-ad68a1b0-6311-462e-a5cf-ca4f0c6fae87.png)

Then in the integrations menu GTM KIT doesn't recognize that EDD is already installed and features cannot be used.
![image](https://user-images.githubusercontent.com/25766885/232853886-e3f83234-b287-4cdc-98ee-e5fcfb6ea896.png)

**Comment by pety-dc** [comment]
It appears that EDD pro changed the directory name from `easy-digital-downloads` to `easy-digital-downloads-pro`

These are the locations the directory name appears:
https://github.com/tlamedia/gtm-kit/search?q=easy-digital-downloads

**Comment by TorbenLundsgaard** [comment]
Can you confirm that the path to the main plugin file of the plugin is: `easy-digital-downloads-pro/easy-digital-downloads.php`

**Comment by pety-dc** [comment]
Hey @TorbenLundsgaard 

I can confirm that the new "pro" folder is `easy-digital-downloads-pro`

![image](https://user-images.githubusercontent.com/25766885/233037810-dd7d5c01-1461-49b9-a1e9-9a3c013439d0.png)


I applied exactly the same changes to our local copy of GTM KIT and it worked properly.

**Comment by TorbenLundsgaard** [comment]
OK. I will merge it.

Thank you for your contribution!
