### ISSUE TITLE
view_item

### ISSUE THREAD

**Issue by aligorhan** [tlamedia/gtm-kit#33]
On variable products the plugin counts view_item event two times.
![variable1](https://user-images.githubusercontent.com/78086791/199036897-f6023549-ce25-4738-b766-2b61c2673b49.png)
![variable2](https://user-images.githubusercontent.com/78086791/199036905-29e6adcf-aaf5-4e0f-8540-dcf3dd52ebf4.png)

**Comment by TorbenLundsgaard** [comment]
This is a tricky one and I’m sure that there are many opinions about what best practice is.

Your first view event is for the master product (136) and the next is for the variation (137). Which would you prefer if there should only be one?

If we don’t push a view event on the master product a user may visit the product page, leave the page and we wouldn’t have registered a view. If we on the other hand don’t push the view the event for the variation, we would have an add_to_cart event for item 137 without a preceding view event for that item.

How do you think it should be handled?

**Comment by aligorhan** [comment]
I noticed that the theme automatically selects the product variant.
I've changed the theme, now it works correctly and only one product is triggered. (Master Product - 136)
