### ISSUE TITLE
Missing wait_for_update parameter

### ISSUE THREAD

**Issue by eickit** [tlamedia/gtm-kit#460]
Hello everyone, the wait_for_update parameter is missing in my script when I specify one. Can anyone confirm this? This generates a javascript error that prevents the event inspector from working.

Best regards Sven

![screenshot_20240511174945](https://github.com/tlamedia/gtm-kit/assets/4112464/8c1b4a78-6c48-4814-b143-ff488b66ac96)

**Comment by TorbenLundsgaard** [comment]
I can confirm the bug and i have made a fix #461

**Comment by TorbenLundsgaard** [comment]
I have just released 1.22.1
