### ISSUE TITLE
[Q] Google Consent Mode-compatible WordPress plugin

### ISSUE THREAD

**Issue by szepeviktor** [tlamedia/gtm-kit#479]
AFAIK GTM Kit does not display an accept/reject cookies dialogue.
What Google Consent Mode-compatible WordPress plugin do you recommend?

**Comment by TorbenLundsgaard** [comment]
I don't know if there are any good and free plugins that support Google Consent Mode.
Complianz is popular but requires the premium plugin for GCM: https://wordpress.org/plugins/complianz-gdpr/

Personally i prefer the CMP https://cookieinformation.com/, which can be implemented in Google Tag Manager.

**Comment by szepeviktor** [comment]
Thank you.
