### ISSUE TITLE
Purchase event not send

### ISSUE THREAD

**Issue by phcaraujo** [tlamedia/gtm-kit#94]
I installed and configured the plugin on my website, however, the purchase event is not being sent to GTM.

All other events work normally: view_item, begin_checkout and add_to_cart

I use the Easy Digital Downloads plugin.

**Comment by TorbenLundsgaard** [comment]
The purchacse event fires if the Confirmation Page is detected: https://github.com/tlamedia/gtm-kit/blob/main/src/Integration/EasyDigitalDownloads.php#L138

The Confirmation Page is set in the Easy Digital Download settings under: Settings > General > Pages > Confirmation Page.

Can you confirm that the  Confirmation Page is set?

**Comment by TorbenLundsgaard** [comment]
I looked a bit deeper and apparently the Confirmation Page is a new page type and older installations may not have this page, so there needs to be a fallback to the old Success Page.

Could you please try the fix i have made an let me know if it works?

**Comment by phcaraujo** [comment]
Actually I don't have this page set up.

The page I have set up is the receipt page.

Do I just need to create this page and select it in the settings or do I need to do something else on this page? Eg: add a shortcode from easy digital downloads itself.

Here's how my page looks: https://i.epvpimg.com/13PKbab.png

**Comment by TorbenLundsgaard** [comment]
Could you please try the fix in #97. I think that should do it.

**Comment by TorbenLundsgaard** [comment]
I have tested my fix with the configuration in your screenshot and it solves the problem. So I will go ahead and merge the fix, which will be included in the next release scheduled for next monday.
